# This is a basic workflow to help you get started with Actions
name: DevDBInstance-Syn
on:
  
  pull_request:
  
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      envname:
        type: choice
        description: 'target environment name '
        required: true
        options:
        - 'oracleoci'
        - 'dev'
        - 'qa'
        - 'uat'
        default: 'oracleoci'
      db-instance-name:
        description: 'database instance name '
        required: true
        default: 'thayeratp'
      db-instance-id:
        description: 'database instance id '
        required: true
        default: 'ocid1.autonomousdatabase.oc1.iad.anuwcljtntxkdlyambke7vkjliaugvioqteeobnp5q7vs5x6hdp56elwczla'
       
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devinstances:
    uses: "./.github/workflows/DBChangesSync.yml"
    
    with:
      envname: oracleoci
      db-instance-name: thayeratp
      db-instance-id: ocid1.autonomousdatabase.oc1.iad.anuwcljtntxkdlyambke7vkjliaugvioqteeobnp5q7vs5x6hdp56elwczla
    

          
         

    
     

