name: "setup sqlcl "
on:
#  schedule:
#    - cron: '*/5 * * * *'
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  my-instances:
    runs-on: self-hosted
    environment: oracleoci
    name: SQLcl Integration
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_FILE: ${{ secrets.OCI_CLI_KEY_FILE }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
      RUNNER_TOOL_CACHE: /thayer/envs/dev
      AGENT_TOOLSDIRECTORY: /thayer/envs/dev
   
    steps:
      - name : setup java
        uses: actions/setup-java@v4
        with:
         distribution: 'oracle'
         java-version: '21'
      - name: 'setup directories'
        working-directory: /thayer/envs/dev
        run: |
          mkdir -p dev2 
          echo "SQLCL_HOME=/thayer/sqlcl/" >> "$GITHUB_ENV"
          # eval version
          CMD="${SQLCL_HOME}/bin/sql -version"
          eval "${CMD}"

          # export
          echo "${SQLCL_HOME}/bin" >> "$GITHUB_PATH
          sql  /nolog 
          set cloudconfig /thayer/Wallet_thayeratp.zip
          connect admin/${{ secrets.DB_PASSWD }}@thayeratp_low

          
         

    
      - name: Retrieve the OCID of a named compartment in tenancy
        uses: oracle-actions/run-oci-cli-command@v1.3.2
        id: find-compartment-id
        with:
          command: 'iam compartment list --compartment-id ocid1.tenancy.oc1..aaaaaaaaplkmid2untpzjcxrmbv4nowe74yb4lr6idtckwo4wyf7jh23be4q'
          silent: true
      
     
      - name: List the display name and shape of the instances in my compartment
        run: |
          echo ${{ steps.find-compartment-id.outputs.output }} | jq .
          echo outputContent=${{ steps.find-compartment-id.outputs.output }} >> $env:GITHUB_OUTPUT
          echo "Bash version: ${{ steps.find-compartment-id.outputs.outputContent }}"
      




