# This is a basic workflow to help you get started with Actions

name: syncdbchangestotargetdbinstance

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs:
      dbinstance-environment:
        description: 'name of the ATP DB instance to push the sql changes- dev,qa,uat,prod etc '
        required: true
        default: 'dev1'
      dbinstance-displayname:
        description: 'ATP database instance display name '
        required: true
        default: 'dev2'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

   build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /thayer/envs/dev
    environment: ${{ inputs.dbinstance-environment}}
    name: SQLcl Integration
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_FILE: ${{ secrets.OCI_CLI_KEY_FILE }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
      AGENT_TOOLSDIRECTORY: "/thayer/envs/${{ inputs.dbinstance-environment}}"
      RUNNER_TOOL_CACHE: "/thayer/envs/${{ inputs.dbinstance-environment}}"
   
    steps:
      - name : setup java
        uses: actions/setup-java@v4
        with:
         distribution: 'oracle'
         java-version: '21'
      
        
        
      - name: 'setup directories'
        working-directory: /thayer/envs/${{ inputs.dbinstance-environment}}
        run: |
          ls -ltr
          echo "SQLCL_HOME=/thayer/sqlcl/" >> "$GITHUB_ENV"
          # eval version
          CMD="${SQLCL_HOME}/bin/sql -version"
          eval "${CMD}"
          # export
          echo "${SQLCL_HOME}/bin" >> $GITHUB_PATH
    
          echo "lb update controller.xml" | sql admin/${{ secrets.DB_PASSWD }}@${{ secrets.DB_Service_Name }}?TNS_ADMIN=/thayer/envs/${{ inputs.dbinstance-environment}}
          

          
         

    
