# This is a basic workflow to help you get started with Actions

name: SynchDBChangesToTargetEnv

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      envname:
        description: 'target environment name '
        required: true
        default: 'dev1'
      db-instance-name:
        description: 'database instance name '
        required: true
        default: 'dev2'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   my-instances:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /thayer/envs/${{ inputs.envname }}
    environment: ${{ inputs.envname }}
    name: SQLcl Integration
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_FILE: ${{ secrets.OCI_CLI_KEY_FILE }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_INSTANCE_ID: ${{ secrets.OCI_INSTANCE_ID }}
      RUNNER_TOOL_CACHE: /thayer/envs/${{ inputs.envname }}
      AGENT_TOOLSDIRECTORY: /thayer/envs/${{ inputs.envname }}
   
    steps:
     
      - name: Use Workspace
        run: ls $GITHUB_WORKSPACE
      - name: checkout dev
        uses: actions/checkout@v4
        with:
         repository: ${{ github.repository }}
         ref: 'dev'
         path: dbinstances/${{ inputs.db-instance-name }}/lbfiles
         token: ${{ github.token }}

      - name: Run a one-line script
        run:  echo "test"
      - name : setup java
        uses: actions/setup-java@v4
        with:
         distribution: 'oracle'
         java-version: '21'
      - name: 'setup directories'
        working-directory: /thayer/envs/${{ inputs.envname }}/dbinstances/${{ inputs.db-instance-name }}
        run: |
          echo "SQLCL_HOME=/thayer/sqlcl/" >> "$GITHUB_ENV"
          # eval version
          CMD="${SQLCL_HOME}/bin/sql -version"
          eval "${CMD}"

          # export
          echo "${SQLCL_HOME}/bin" >> $GITHUB_PATH
        
          echo "lb update controller.xml" | sql ${{ secrets.DB_USERNAME }}/${{ secrets.format('DB_{0}', inputs.db-instance-name)_PASSWD }}@${{ secrets.format('DB_{0}', inputs.db-instance-name)_SERVICENAME }}?TNS_ADMIN=/thayer/envs/${{ inputs.envname }}/dbinstances/${{ inputs.db-instance-name }}
          

          
         

    
     



